# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'id.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Screen_name = QtWidgets.QLabel(self.centralwidget)
        self.Screen_name.setGeometry(QtCore.QRect(250, 90, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Screen_name.setFont(font)
        self.Screen_name.setFrameShape(QtWidgets.QFrame.Box)
        self.Screen_name.setObjectName("Screen_name")
        self.Button_find = QtWidgets.QPushButton(self.centralwidget)
        self.Button_find.setGeometry(QtCore.QRect(50, 180, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_find.setFont(font)
        self.Button_find.setObjectName("Button_find")
        self.Screen_age = QtWidgets.QLabel(self.centralwidget)
        self.Screen_age.setGeometry(QtCore.QRect(250, 180, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Screen_age.setFont(font)
        self.Screen_age.setFrameShape(QtWidgets.QFrame.Box)
        self.Screen_age.setObjectName("Screen_age")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 141, 51))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.Screen_ID = QtWidgets.QTextEdit(self.centralwidget)
        self.Screen_ID.setGeometry(QtCore.QRect(50, 90, 181, 61))
        self.Screen_ID.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.Screen_ID.setObjectName("Screen_ID")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Screen_name.setText(_translate("MainWindow", "name"))
        self.Button_find.setText(_translate("MainWindow", "find"))
        self.Screen_age.setText(_translate("MainWindow", "age"))
        self.label.setText(_translate("MainWindow", "TD code"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
